# Generated by Django 2.1.2 on 2018-11-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruleengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='rule_signal',
            new_name='signal_id',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='rule_condition',
            new_name='varcondition',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='rule_vartype',
            new_name='vartype',
        ),
    ]
